{% set version = "0.2-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlgt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rlgt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rlgt/Rlgt_{{ version }}.tar.gz
  sha256: ffb75ed4e7008011ab055e2ffd50a274f00348814357f95a3063099e397543b0

build:
  merge_build_host: true  # [win]
  number: 0
  # Makevars.win:18: recipe for target 'stan_files/SGT.cc' failed
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh >=1.66.0
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.2
    - r-stanheaders >=2.18.0
    - r-forecast
    - r-rstan >=2.18.1
    - r-rstantools
    - r-sn
    - r-truncnorm
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    #- r-bh >=1.66.0
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.2
    #- r-stanheaders >=2.18.0
    - r-forecast
    - r-rstan >=2.18.1
    - r-rstantools
    - r-sn
    - r-truncnorm

test:
  commands:
    - $R -e "library('Rlgt')"           # [not win]
    - "\"%R%\" -e \"library('Rlgt')\""  # [win]

about:
  home: https://github.com/cbergmeir/Rlgt
  license: GPL-3.0-only
  summary: An implementation of a number of Global Trend models for time series forecasting that are Bayesian generalizations and extensions of some Exponential Smoothing models. The main differences/additions include 1) nonlinear global trend, 2) Student-t error distribution, and 3) a function for the error size, so heteroscedasticity.
    The methods are particularly useful for short time series. When tested on the well-known M3 dataset, they are able to outperform all classical time series algorithms. The models are fitted with MCMC using the 'rstan' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
